# Generated by Django 2.1.3 on 2018-11-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181126_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
